vim.api.nvim_set_keymap("n", "<C-t>", ":NERDTreeToggle<CR>", { noremap = true })
vim.g.NERDTreeQuitOnOpen=1
vim.g.NERDTreeGitStatusUseNerdFonts = 1
vim.g.NERDTreeFileExtensionHighlightFullName = 1
vim.g.NERDTreeExactMatchHighlightFullName = 1
vim.g.NERDTreePatternMatchHighlightFullName = 1
-- vim.g.WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['tex']    = ' '
-- vim.g.WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['cs']     = '󰌛 '
-- vim.g.WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['r']      = '󰟔 '
-- vim.g.WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['rproj']  = '󰗆 '
-- vim.g.WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['sol']    = '󰡪 '
-- vim.g.WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['pem']    = '󰌋 '
-- vim.g.WebDevIconsUnicodeDecorateFileNodesExactSymbols['robots.txt'] = '󰋚 '
