version = 1

[*]
flash-attn = on

[unsloth/Qwen3.8-27B-GGUF:UD-Q8_K_XL]
n-gpu-layers = all
chat-template-file = /root/.cache/huggingface/hub/models--froggeric--Qwen-Fixed-Chat-Templates/snapshots/3be7669fac73085a458e20e81ee9dc5c322aefb2/chat_template.jinja
ctx-size = 98304
ctk = q8_0
ctv = q8_0
tensor-split = 24,13
spec-type = draft-mtp
spec-draft-n-max = 3
temperature = 1.0
min-p = 0.00
top-p = 0.95
top-k = 20
repeat-penalty = 1.0
presence-penalty = 0.0
reasoning-preserve = 1

[unsloth/Qwen3.8-27B-GGUF:UD-Q8_K_XL-dflash2]
n-gpu-layers = all
hf-repo = unsloth/Qwen3.8-27B-GGUF:UD-Q8_K_XL
chat-template-file = /root/.cache/huggingface/hub/models--froggeric--Qwen-Fixed-Chat-Templates/snapshots/3be7669fac73085a458e20e81ee9dc5c322aefb2/chat_template.jinja
mmproj = /root/.cache/huggingface/hub/models--unsloth--Qwen3.8-27B-GGUF/snapshots/4ca720788d1e01f1bff70c033e0d0028fd02e502/mmproj-BF16.gguf
ctx-size = 81920
; ctx-size = 98304
ctk = q8_0
ctv = q8_0
tensor-split = 24,14
spec-type = draft-dflash
spec-draft-model = /root/.cache/huggingface/hub/models--HermiHg--Qwen3.8-27B-DFlash2-Q2_K_S-MIX-GGUF/snapshots/83ec94ea5162dbd01b4e891d94b42fc09bf805de/Qwen3.8-27B-DFlash2-Q2_K_S-MIX.gguf
spec-draft-n-max = 5
temperature = 1.0
min-p = 0.00
top-p = 0.95
top-k = 20
repeat-penalty = 1.0
presence-penalty = 0.0
reasoning-preserve = 1

[bartowski/Qwen3.8-27B-GGUF:Q8_0]
n-gpu-layers = all
hf-repo = bartowski/Qwen3.8-27B-GGUF:Q8_0
chat-template-file = /root/.cache/huggingface/hub/models--froggeric--Qwen-Fixed-Chat-Templates/snapshots/3be7669fac73085a458e20e81ee9dc5c322aefb2/chat_template.jinja
; ctx-size = 81920
ctx-size = 98304
reasoning-budget = 8192
; ctx-size = 131072
ctk = q8_0
ctv = q8_0
; tensor-split = 24,15
; spec-type = draft-mtp
; spec-draft-n-max = 3
spec-type = draft-dflash
spec-draft-model = /root/.cache/huggingface/hub/models--HermiHg--Qwen3.8-27B-DFlash2-Q2_K_S-MIX-GGUF/snapshots/83ec94ea5162dbd01b4e891d94b42fc09bf805de/Qwen3.8-27B-DFlash2-Q2_K_S-MIX.gguf
spec-draft-n-max = 7
temperature = 1.0
min-p = 0.00
top-p = 0.95
top-k = 20
repeat-penalty = 1.0
presence-penalty = 0.0
reasoning-preserve = 1

[unsloth/Qwen3.8-Flash-Next-GGUF:UD-IQ4_XS]
hf-repo = unsloth/Qwen3.8-Flash-Next-GGUF:UD-IQ4_XS
chat-template-file = /root/.cache/huggingface/hub/models--froggeric--Qwen-Fixed-Chat-Templates/snapshots/3be7669fac73085a458e20e81ee9dc5c322aefb2/chat_template.jinja
ctx-size = 262144
ctk = q8_0
ctv = q8_0
fit = on
; spec-type = draft-mtp
; spec-draft-n-max = 3
temperature = 1.0
min-p = 0.00
top-p = 0.95
top-k = 20
repeat-penalty = 1.0
presence-penalty = 0.0
reasoning-preserve = 1

[unsloth/Qwen3.8-Flash-Next-GGUF:UD-Q4_K_XL]
hf-repo = unsloth/Qwen3.8-Flash-Next-GGUF:UD-Q4_K_XL
chat-template-file = /root/.cache/huggingface/hub/models--froggeric--Qwen-Fixed-Chat-Templates/snapshots/3be7669fac73085a458e20e81ee9dc5c322aefb2/chat_template.jinja
ctx-size = 262144
ctk = q8_0
ctv = q8_0
fit = on
; spec-type = draft-mtp
; spec-draft-n-max = 3
temperature = 1.0
min-p = 0.00
top-p = 0.95
top-k = 20
repeat-penalty = 1.0
presence-penalty = 0.0
reasoning-preserve = 1
