# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  unstable = import <nixpkgs-unstable> { config.allowUnfree = true; };
in

{
  # Hardware configuration
  hardware = {
    bluetooth.enable = true;
    enableRedistributableFirmware = true;
    graphics = {
      enable = true;
      extraPackages = with pkgs; [ intel-media-driver ];
    };
    i2c.enable = true;
    nvidia = {
      # Modesetting is required.
      # modesetting.enable = true;

      # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
      # Enable this if you have graphical corruption issues or application crashes after waking
      # up from sleep. This fixes it by saving the entire VRAM memory to /tmp/ instead 
      # of just the bare essentials.
      powerManagement.enable = true;

      # Fine-grained power management. Turns off GPU when not in use.
      # Experimental and only works on modern Nvidia GPUs (Turing or newer).
      powerManagement.finegrained = false;

      # Use the NVidia open source kernel module (not to be confused with the
      # independent third-party "nouveau" open source driver).
      # Support is limited to the Turing and later architectures. Full list of 
      # supported GPUs is at: 
      # https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus 
      # Only available from driver 515.43.04+
      # Currently alpha-quality/buggy, so false is currently the recommended setting.
      open = true;

      # Enable the Nvidia settings menu,
      # accessible via `nvidia-settings`.
      nvidiaSettings = true;

      # Optionally, you may need to select the appropriate driver version for your specific GPU.
      # package = config.boot.kernelPackages.nvidiaPackages.latest;
      # package = unstable.linuxPackages_latest.nvidiaPackages.stable;
      # package = config.boot.kernelPackages.nvidiaPackages.stable;
      # package = config.boot.kernelPackages.nvidiaPackages.mkDriver {
      #   version = "570.124.04"; # use new 570 drivers
      #   sha256_64bit = "sha256-G3hqS3Ei18QhbFiuQAdoik93jBlsFI2RkWOBXuENU8Q=";
      #   openSha256 = "sha256-DuVNA63+pJ8IB7Tw2gM4HbwlOh1bcDg2AN2mbEU9VPE=";
      #   settingsSha256 = "sha256-9rtqh64TyhDF5fFAYiWl3oDHzKJqyOW3abpcf2iNRT8=";
      #   usePersistenced = false;
      # };
    };
    nvidia-container-toolkit.enable = true;
    # nvidia.prime = {
    #   offload = {
    #     enable = true;
    #     enableOffloadCmd = true;
    #   };
    #   intelBusId = "PCI:0:2:0";
    #   nvidiaBusId = "PCI:1:0:0";
    # };
    cpu.intel.updateMicrocode =
      lib.mkDefault config.hardware.enableRedistributableFirmware;
  };

  # Boot configuration
  boot = {
    initrd.availableKernelModules =
      [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
    initrd.kernelModules = [ ];
    initrd.systemd.enable = true;
    initrd.verbose = false;
    kernelModules = [ "kvm-intel" "i2c-dev" ];
    # boot.extraModulePackages = [ ];
    loader.systemd-boot.consoleMode = "max";
    loader.timeout = 0;
    kernelParams = [
      "quiet"
      "splash"
      "boot.shell_on_fail"
      "rd.systemd.show_status=auto"
      "udev.log_priority=3"
    # "nvidia.NVreg_PreserveVideoMemoryAllocations=1"
    # "nvidia.NVreg_EnableGpuFirmware=0"
    # "nvidia-drm.modeset=1"
    # "nvidia-drm.fbdev=1"
    ];
    # kernelPackages = pkgs.linuxPackages_6_13;
    kernelPackages = pkgs.linuxPackages_latest;
  };

  # File systems
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/93e624aa-5323-466d-9dc8-b395a78efef1";
    fsType = "btrfs";
    options = [ "subvol=root" "compress=zstd" ];
  };
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/93e624aa-5323-466d-9dc8-b395a78efef1";
    fsType = "btrfs";
    options = [ "subvol=home" "compress=lzo" ];
  };
  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/93e624aa-5323-466d-9dc8-b395a78efef1";
    fsType = "btrfs";
    options = [ "subvol=nix" "compress=zstd" "noatime" ];
  };
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/36FE-D52D";
    fsType = "vfat";
  };

  # Network configuration
  networking = {
    hostName = "homepc"; # Define your hostname.
    useDHCP = lib.mkDefault true;
    # interfaces.enp3s0.mtu = 9000;
    wireless.enable =
      lib.mkForce false; # Enables wireless support via wpa_supplicant.
  };

  # Nix configuration
  nixpkgs.config.cudaSupport = true;

  # Security configuration
  security = {
    rtkit.enable = true;
    wrappers = {
      btop = {
        enable = true;
        owner = "root";
        group = "root";
        source = "${unstable.btop-cuda}/bin/btop";
        capabilities = "cap_perfmon=ep";
      };
    };
  };

  # Services
  services = {
    openssh.enable = true;
    pipewire = {
      enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      pulse.enable = true;
      # extraConfig.pipewire."91-combined-sinks" = {
      #   "context.modules" = [
      #     {
      #       name = "libpipewire-module-combine-stream";
      #       args = {
      #         combine.mode = "sink";
      #         node.name = "combined_sink";
      #         node.description = "My Combined Sink";
      #         combine.latency-compensate = false;
      #         combine.props = {
      #           audio.position = [ "FL" "FR" ];
      #         };
      #         stream.props = {
      #           stream.dont-remix = true;
      #         };
      #         stream.rules = [
      #           {
      #             matches = [
      #               {
      #                 media.class = "Audio/Sink";
      #                 node.name = "alsa_output.pci-0000_01_00.1.pro-output-3";
      #               }
      #             ];
      #             actions = {
      #               create-stream = {
      #                 audio.position = [ "FL" "FR" ];
      #                 combine.audio.position = [ "FL" "FR" ];
      #               };
      #             };
      #           }
      #           {
      #             matches = [
      #               {
      #                 media.class = "Audio/Sink";
      #                 node.name = "alsa_output.pci-0000_01_00.1.pro-output-7";
      #               }
      #             ];
      #             actions = {
      #               create-stream = {
      #                 audio.position = [ "FL" "FR" ];
      #                 combine.audio.position = [ "FL" "FR" ];
      #               };
      #             };
      #           }
      #         ];
      #       };
      #     }
      #   ];
      # };
    };
    thermald.enable = true;
    xserver = {
      videoDrivers = [ 
        "modesetting"
        "nvidia" 
      ];
    };
  };

  # Systemd configuration
  systemd = {
    sleep.extraConfig = ''
      AllowSuspend=yes
      AllowHibernation=no
      AllowHybridSleep=no
      AllowSuspendThenHibernate=no
    '';
    services.nvidia_oc = {
      enable = true;
      description = "NVidia overclock settings";
      serviceConfig = {
        ExecStart =
          "${pkgs.nvidia_oc}/bin/nvidia_oc set --index 0 --mem-offset 2000 --freq-offset 400";
        ExecStop =
          "${pkgs.nvidia_oc}/bin/nvidia_oc set --index 0 --mem-offset 0 --freq-offset 0";
        RemainAfterExit = true;
      };
    };

    # shows wattage in btop for intel cpus
    tmpfiles.rules = ["Z /sys/class/powercap/intel-rapl:0/energy_uj 0444 root root - -"];
  };

  # Environment configuration
  environment.systemPackages = [ pkgs.nvidia_oc pkgs.nvtopPackages.nvidia unstable.btop-cuda];

  # System configuration
  swapDevices = [{
    device = "/swapfile";
    size = 32 * 1024; # 32GB
  }];

  # Virtualization configuration
  virtualisation.oci-containers = {
    backend = "podman";
    containers = {
      # qwen3-coder-next = {
      #   autoStart = true;
      #   image = "ghcr.io/ggml-org/llama.cpp:server-cuda13";
      #   cmd = [
      #     "-hf"
      #     # "unsloth/Qwen3-Coder-Next-GGUF:UD-IQ3_XXS"
      #     "unsloth/Qwen3-Coder-Next-GGUF:UD-Q4_K_XL"
      #     "--port"
      #     "8080"
      #     "--temp"
      #     "1.0"
      #     "--min-p"
      #     "0.01"
      #     "--top-p"
      #     "0.95"
      #     "--top-k"
      #     "40"
      #     "--ctx-size"
      #     "65535"
      #     "--no-mmap"
      #     "--fit"
      #     "on"
      #     "--fit-ctx"
      #     "65535"
      #     "-ctk"
      #     "q8_0"
      #     "-ctv"
      #     "q8_0"
      #     "--jinja"
      #     "--fit-target"
      #     "3072"
      #   ];
      #   ports = [ "8080:8080" ];
      #   devices = [ "nvidia.com/gpu=all" ];
      #   volumes = [ "/home/javi/.cache/huggingface:/root/.cache/huggingface" ];
      #   pull = "newer";
      # };
      qwen36 = {
        autoStart = true;
        image = "ghcr.io/ggml-org/llama.cpp:server-cuda13";
        cmd = [
          "-hf"
          # "unsloth/Qwen3.6-35B-A3B-GGUF:UD-Q8_K_XL"
          # "unsloth/Qwen3.6-35B-A3B-GGUF:MXFP4_MOE"
          # "unsloth/Qwen3.6-27B-GGUF:UD-IQ3_XXS"
          # "rico03/Qwen3.6-27B-Claude-Opus-Reasoning-Distilled-GGUF:Q3_K_M"
          "HauhauCS/Qwen3.6-27B-Uncensored-HauhauCS-Aggressive:IQ3_M"
          "--port"
          "8080"
          "--temp"
          "0.6"
          "--min-p"
          "0.00"
          "--top-p"
          "0.95"
          "--top-k"
          "20"
          "--repeat-penalty"
          "1.0"
          "--presence-penalty"
          "0.0"
          "--ctx-size"
          # "262144"
          # "98304"
          "65535"
          "--no-mmap"
          "-ctk"
          "q4_0"
          "-ctv"
          "q4_0"
          "-ngl"
          "99"
          # "--fit-target"
          # "1024"
          # "--fit"
          # "on"
          # "--fit-ctx"
          # "262144"
          # "65535"
        ];
        ports = [ "8080:8080" ];
        devices = [ "nvidia.com/gpu=all" ];
        volumes = [ "/home/javi/.cache/huggingface:/root/.cache/huggingface" ];
        pull = "newer";
      };
      # fim = {
      #   autoStart = true;
      #   image = "ghcr.io/ggml-org/llama.cpp:server-cuda13";
      #   cmd = [
      #     "--fim-qwen-1.5b-default"
      #     "-ngl"
      #     "99"
      #   ];
      #   ports = [ "8012:8012" ];
      #   devices = [ "nvidia.com/gpu=all" ];
      #   volumes = [ "/home/javi/.cache/huggingface:/root/.cache/huggingface" ];
      #   pull = "newer";
      # };
    };
  };

  imports =
    [ ../common.nix (modulesPath + "/installer/scan/not-detected.nix") ];
}
