# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  # modulesPath,
  unstable,
  ...
}:

let
  # --- TEMPORARY iwlwifi firmware test (DISABLED 2026-09-20, rolled back
  # --- to stock linux-firmware / c106). Un-comment this binding + the
  # --- enableRedistributableFirmware/firmware overrides below to force
  # --- the driver to load c102 again (hides c106 + c103).
  # linuxFirmwareNoC102Newer = pkgs.runCommand "linux-firmware-no-iwlwifi-c103-c106"
  #   { src = pkgs.linux-firmware; } ''
  #   cp -r $src/. $out
  #   chmod -R u+w $out
  #   rm -f $out/lib/firmware/iwlwifi-gl-c0-fm-c0-c106.ucode
  #   rm -f $out/lib/firmware/iwlwifi-gl-c0-fm-c0-c103.ucode
  # '';
in
{
  # Hardware configuration
  hardware = {
    bluetooth.enable = true;
    # TEMPORARY iwlwifi firmware test (see let-block at top) — DISABLED:
    # enableRedistributableFirmware = lib.mkForce false;
    # firmware = with pkgs; [
    #   linuxFirmwareNoC102Newer
    #   ipw2200-firmware
    #   rtl8192su-firmware
    #   rt5677-firmware
    #   rtl8761b-firmware
    #   zd1211fw
    #   alsa-firmware
    #   sof-firmware
    #   libreelec-dvb-firmware
    # ];
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        intel-media-driver
        vpl-gpu-rt
      ];
    };
    i2c.enable = true;
    nvidia = {
      # Modesetting is required.
      # modesetting.enable = true;

      # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
      # Enable this if you have graphical corruption issues or application crashes after waking
      # up from sleep. This fixes it by saving the entire VRAM memory to /tmp/ instead
      # of just the bare essentials.
      powerManagement.enable = true;

      # Fine-grained power management. Turns off GPU when not in use.
      # Experimental and only works on modern Nvidia GPUs (Turing or newer).
      powerManagement.finegrained = false;

      # Use the NVidia open source kernel module (not to be confused with the
      # independent third-party "nouveau" open source driver).
      # Support is limited to the Turing and later architectures. Full list of
      # supported GPUs is at:
      # https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus
      # Only available from driver 515.43.04+
      # Currently alpha-quality/buggy, so false is currently the recommended setting.
      open = true;

      # Enable the Nvidia settings menu,
      # accessible via `nvidia-settings`.
      nvidiaSettings = true;

      # Optionally, you may need to select the appropriate driver version for your specific GPU.
      # 2026-09-24: kernel AND driver both from `unstable.linuxPackages_6_18`
      # (6.18.53 LTS + nvidia 615.71.09 / CUDA 13.4) — LTS kernel (no EOL
      # whiplash) with the newest driver branch, both prebuilt on
      # cache.nixos.org (verified: 6.18 open module = fetch-only).
      # History: 2026-09-22 this was `unstable.linuxPackages_7_2` (7.2.7 +
      # 615.71.09) — fully prebuilt, but 7.2 is non-LTS: no upstream patches
      # once 7.3 lands, and nixpkgs drops EOL series (7.0 already gone).
      # The nixos-26.05 release channel prebuilds nvidia for 6.12/6.18 but
      # only at 595.71.05 (CUDA 12.x) — a downgrade that would break the
      # CUDA-13 llama-cuda container — so the driver must come from unstable.
      # Kernel + driver must stay from the SAME set (mixing once broke with
      # "inconsistent kernel versions" in the modules aggregator).
      package = unstable.linuxPackages_6_18.nvidiaPackages.latest;
      # package = config.boot.kernelPackages.nvidiaPackages.beta;
      # package = config.boot.kernelPackages.nvidiaPackages.mkDriver {
      #   version = "570.124.04"; # use new 570 drivers
      #   sha256_64bit = "sha256-G3hqS3Ei18QhbFiuQAdoik93jBlsFI2RkWOBXuENU8Q=";
      #   openSha256 = "sha256-DuVNA63+pJ8IB7Tw2gM4HbwlOh1bcDg2AN2mbEU9VPE=";
      #   settingsSha256 = "sha256-9rtqh64TyhDF5fFAYiWl3oDHzKJqyOW3abpcf2iNRT8=";
      #   usePersistenced = false;
      # };
    };
    nvidia-container-toolkit.enable = true;
    # nvidia.prime = {
    #   offload = {
    #     enable = true;
    #     enableOffloadCmd = true;
    #   };
    #   intelBusId = "PCI:0:2:0";
    #   nvidiaBusId = "PCI:1:0:0";
    # };
  };

  # Boot configuration
  boot = {
    # pci-stub claims the two headless NVIDIA HDMI-audio functions (GB203
    # 10de:22e9 on the 5070 Ti, GA102 10de:1aef on the 3090 Ti) so that
    # snd_hda_intel can never bind them. Their codecs are power-gated (no
    # display is plugged into either GPU), so the first HDA verb times out:
    #   snd_hda_intel 0000:03:00.1: azx_get_response timeout, switching to polling mode
    #   irq 17: nobody cared ... Disabling IRQ #17
    # MSI is disabled for both (vga_switcheroo audio client), forcing them onto
    # the shared legacy PIC IRQ 17, which the kernel masked after ~200k
    # unhandled interrupts. Loaded in the initrd so the claim happens before
    # snd_hda_intel is even loadable. Audio output is unaffected: the sinks are
    # the iGPU/PCH ACE HDMI (card3) plus the USB Audio interface. To revert,
    # drop these entries and the pci-stub.ids / driver_override rules below.
    initrd.availableKernelModules = [ "pci-stub" ];
    initrd.kernelModules = [ "pci-stub" ];
    initrd.systemd.enable = true;
    initrd.verbose = false;
    kernelModules = [ "i2c-dev" "pci-stub" ];
    # boot.extraModulePackages = [ ];
    loader.systemd-boot.consoleMode = "max";
    loader.timeout = 0;
    kernelParams = [
      "quiet"
      "splash"
      "boot.shell_on_fail"
      "rd.systemd.show_status=auto"
      "udev.log_priority=3"
      "reboot=pci,cold"
      # IDs for pci-stub to claim when it loads (the cmdline reaches it in both
      # the initrd and the root system). See the pci-stub comment above.
      "pci-stub.ids=10de:22e9,10de:1aef"
      # "pcie_aspm.policy=performance"
      # "pcie_aspm.policy=powersupersave"
      # "pci=assign-busses,hpbussize=0x33,realloc,hpmmiosize=128M,hpmmioprefsize=1G"
      # "pci=realloc"
      # "pcie_aspm=off"
      # "pcie_port_pm=off"
      # "nvidia.NVreg_PreserveVideoMemoryAllocations=1"
      # "nvidia-drm.modeset=1"
      # "nvidia-drm.fbdev=1"
    ];
    kernelPackages = unstable.linuxPackages_6_18; # 2026-09-24: 6.18 LTS (6.18.53) from unstable — must match hardware.nvidia.package (same linuxPackages_6_18 set); see the comment there for the full history (was 7.2 non-LTS)
    blacklistedKernelModules = [ "spd5118" ];
    # extraModprobeConfig = ''
    #   options nvidia NVreg_PreserveVideoMemoryAllocations=0
    #   (disabled - powerManagement.enable = false handles this)
    # '';
    kernel.sysctl = {
      "vm.blockdev.readahead" = "2048";
    };
  };

  # Network configuration
  networking = {
    hostName = "homepc"; # Define your hostname.
    useDHCP = lib.mkDefault true;
    # interfaces.enp3s0.mtu = 9000;
    # wireless.enable = lib.mkForce false; # Enables wireless support via wpa_supplicant.
  };

  # Nix configuration
  nixpkgs.config.cudaSupport = true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Virtualisation configuration
  # Run QEMU as unprivileged user qemu-libvirtd (fixes the libvirt
  # "tainted: running with undesirable elevated privileges" warning).
  # Guest files must be owned by qemu-libvirtd (see /home/javi/images/omarchy-vm).
  virtualisation.libvirtd.qemu.runAsRoot = false;

  # Search-only access to $HOME so qemu-libvirtd can reach the VM images
  # in /home/javi/images/omarchy-vm (no list/read granted).
  users.users.javi.homeMode = "751";

  # Security configuration
  security = {
    rtkit.enable = true;
    wrappers = {
      btop = {
        enable = true;
        owner = "root";
        group = "root";
        source = "${unstable.btop-cuda}/bin/btop";
        capabilities = "cap_perfmon=ep";
      };
    };
  };

  # Services
  services = {
    hardware.bolt.enable = true;
    lact = {
      enable = true;
      package = unstable.lact;
    };
    openssh.enable = true;
    pipewire = {
      enable = true;
      alsa.enable = true;
      alsa.support32Bit = true;
      pulse.enable = true;
    };
    thermald.enable = true;
    udev.extraRules = ''
      ACTION=="add|change", KERNEL=="nvme0n1", ATTR{queue/read_ahead_kb}="2048"
      SUBSYSTEM=="usb", ATTR{idVendor}=="0955", MODE="0664", GROUP="plugdev"
      # The BE200 MLD driver re-registers under a new wiphy index every time
      # the iwlwifi-reload system-sleep hook runs, which would otherwise make
      # the interfaces appear as wlan2, wlan3, ... Pin the two card MACs to
      # stable names. iwd follows the device by wiphy, so the (variable)
      # station interface name is not functionally important.
      SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="e8:bf:b8:5a:41:55", NAME="wlan0"
      SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="e8:bf:b8:5a:41:56", NAME="wlan1"
      # Belt and braces for the pci-stub claim above: only pci-stub may ever
      # match these two HDA functions, so a manual `echo 1 > /sys/bus/pci/rescan`
      # or a hot re-bind can't put snd_hda_intel back on the legacy IRQ 17.
      SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{device}=="0x22e9", ATTR{driver_override}="pci-stub"
      SUBSYSTEM=="pci", ATTR{vendor}=="0x10de", ATTR{device}=="0x1aef", ATTR{driver_override}="pci-stub"
    '';

    xserver = {
      videoDrivers = [
        "modesetting"
        "nvidia"
      ];
    };
  };

  # The Intel Wi-Fi 7 BE200 (iwlmld) firmware state gets corrupted by
  # suspend/resume: the link stays nominal (80MHz 2x2, no retries) but
  # throughput collapses (~25 up / ~320 down on a 600/600 line) until the
  # driver is fully reloaded. Unload the wifi stack before suspend and
  # reload it after resume so the firmware is re-initialized cleanly on
  # every cycle — equivalent to a reboot, without one. iwd reconnects
  # automatically after the module reloads.
  # 2026-09-24: DISABLED to test whether kernel 6.18.53 (LTS) fixes the
  # BE200 suspend/resume issue without the reload workaround. If throughput
  # collapses again after a suspend cycle, un-comment this block.
  # environment.etc."systemd/system-sleep/iwlwifi-reload" = {
  #   source = "${pkgs.writeShellScriptBin "iwlwifi-reload" ''
  #     export PATH=/run/current-system/sw/bin:/run/booted-system/sw/bin:/usr/sbin:/usr/bin:/sbin:/bin
  #     case "$1/$2" in
  #       pre/*)
  #         # The BE200 (MLD) driver registers multiple wlan* interfaces;
  #         # bring them all down so the modules unload cleanly.
  #         for i in /sys/class/net/wlan*; do
  #           ip link set "$(basename "$i")" down 2>/dev/null
  #         done
  #         modprobe -r iwlmld iwlwifi 2>/dev/null
  #         ;;
  #       # NOTE: systemd calls post hooks as "post <sleep-type>" (e.g.
  #       # "post suspend"), so match any post action here.
  #       post/*)
  #         # Reload; iwd re-creates the interfaces and reconnects on its
  #         # own (the station may come back as wlan0 or wlan1).
  #         modprobe iwlmld 2>/dev/null
  #         ;;
  #     esac
  #   ''}/bin/iwlwifi-reload";
  # };

  # Systemd configuration
  systemd = {
    sleep.settings.Sleep = {
      AllowSuspend = true;
      AllowHibernation = false;
      AllowHybridSleep = false;
      AllowSuspendThenHibernate = false;
    };

    # shows wattage in btop for intel cpus
    tmpfiles.rules = [ "Z /sys/class/powercap/intel-rapl:0/energy_uj 0444 root root - -" ];

    services = {
      llamacpp = {
        description = "llama.cpp server container";
        wantedBy = [ "multi-user.target" ];
        serviceConfig = {
          Type = "simple";
          Restart = "on-failure";
          RestartSec = "5s";
          User = "javi";
          Group = "users";
          Environment = [
            "PATH=/run/current-system/sw/bin"
            "CONTAINER_HOST=unix:///run/user/1000/podman/podman.sock"
          ];
        };

        # script = ''
        #   podman run \
        #     --replace \
        #     --name llamacpp \
        #     --pull newer \
        #     --network host \
        #     --device nvidia.com/gpu=all \
        #     -v /home/javi/.cache/huggingface:/root/.cache/huggingface \
        #     -v /home/javi/.config/llamacpp/llama-preset.ini:/app/llama-preset.ini:ro \
        #     ghcr.io/ggml-org/llama.cpp:server-cuda \
        #     --models-preset /app/llama-preset.ini \
        #     --models-max 1 \
        #     -lv 5 \
        #     -t 8 \
        #     -tb 8
        # '';
        script = ''
          # Local build: branch local/mtp-qwen4exp = master @ 6e316de29
          # + patches/mtmd-dflash-mrope-fix.patch (fixes #27408: dflash + mtmd image
          # decoding 500s) + merge of ggml-org/llama.cpp#28243 (qwen4exp MTP draft
          # load + tensor borrow, needed for Qwen3.8-Flash-Next MTP heads).
          # Rebuild via ~/dev/personal/llama.cpp/build-patched.sh <tag>.
          podman run \
            --replace \
            --name llamacpp \
            -p 8080:8080 \
            --device nvidia.com/gpu=all \
            -e GGML_CUDA_ALLREDUCE=internal \
            -e CUDA_VISIBLE_DEVICES=1,0 \
            -v /home/javi/.cache/huggingface:/root/.cache/huggingface \
            -v /home/javi/.config/llamacpp/llama-preset.ini:/app/llama-preset.ini:ro \
            localhost/llama-cuda:mtmd-fix-mtp \
            --models-preset /app/llama-preset.ini \
            --models-max 1 \
            -lv 4 \
            -t 8 \
            -tb 8
        '';
      };

      # llamacpp-npu = {
      #   description = "llama.cpp server container on Intel NPU (OpenVINO backend)";
      #   wantedBy = [ "multi-user.target" ];
      #   serviceConfig = {
      #     Type = "simple";
      #     Restart = "on-failure";
      #     RestartSec = "5s";
      #     User = "javi";
      #     Group = "users";
      #     Environment = [
      #       "PATH=/run/current-system/sw/bin"
      #       "CONTAINER_HOST=unix:///run/user/1000/podman/podman.sock"
      #     ];
      #   };
      #
      #   script = ''
      #     # llama.cpp with OpenVINO backend (official image), NPU via /dev/accel
      #     # (render group = 303). OpenAI API on :8090 -> container :8080.
      #     podman run \
      #       --replace \
      #       --name llamacpp-npu \
      #       -p 8090:8080 \
      #       --device /dev/accel \
      #       -e GGML_OPENVINO_DEVICE=NPU \
      #       --group-add 303 \
      #       -v /home/javi/.cache/huggingface:/root/.cache/huggingface \
      #       -v /home/javi/.config/llamacpp-npu/llama-preset.ini:/app/llama-preset.ini:ro \
      #       ghcr.io/ggml-org/llama.cpp:server-openvino \
      #       --no-warmup \
      #       --models-preset /app/llama-preset.ini \
      #       --models-max 1 \
      #       -lv 5 \
      #       -t 8 \
      #       -tb 8
      #   '';
      # };

      llamacpp-sleep-guard = {
        description = "Stop llamacpp before NVIDIA suspend, restart after resume";
        unitConfig = {
          Before = [ "nvidia-suspend.service" "sleep.target" ];
          StopWhenUnneeded = true;
        };
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStart = "-${config.systemd.package}/bin/systemctl stop llamacpp.service";
          ExecStop = "-${pkgs.systemd}/bin/systemctl start llamacpp.service";
        };
        wantedBy = [ "sleep.target" ];
      };

      # hermes = {
      #   description = "Hermes Agent container";
      #   wantedBy = [ "default.target" ];
      #   serviceConfig = {
      #     Type = "simple";
      #     Restart = "on-failure";
      #     RestartSec = "5s";
      #     User = "javi";
      #     Group = "users";
      #     Environment = "PATH=/run/current-system/sw/bin";
      #     ExecStartPost = "/bin/sh -c 'sleep 5 && ${config.virtualisation.podman.package}/bin/podman cp /home/javi/.config/hermes/config.yaml hermes:/opt/data/config.yaml && ${config.virtualisation.podman.package}/bin/podman exec hermes chown -R hermes:hermes /opt/data || true'";
      #   };

      #   script = ''
      #     podman run \
      #       --replace \
      #       --name hermes \
      #       -v /home/javi/.local/hermes:/opt/data \
      #       nousresearch/hermes-agent:latest \
      #       gateway run
      #   '';
      # };
    };
  };

  # Environment configuration
  environment.systemPackages = [
    pkgs.jellyfin-media-player
    pkgs.level-zero
    pkgs.libmtp
    pkgs.nvidia_oc
    pkgs.nvtopPackages.nvidia
    unstable.btop-cuda
  ];
  environment.etc."lact/config.yaml".source =
    "${config.users.users.javi.home}/.config/lact/config.yaml";

  imports = [
    ../common.nix
    ./hardware-configuration.nix
    # ./openvino.nix
    # ./greencurve.nix
  ];
}
